<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.1;netstandard2.0;netstandard2.1;net45;net461;net462;net7.0;net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>obj/$(Configuration)/$(TargetFramework)/Generated</CompilerGeneratedFilesOutputPath>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/davidxuang/SortSharp</RepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <CheckNotRecommendedTargetFramework>false</CheckNotRecommendedTargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup>
    <SystemVersion4>4.5.*</SystemVersion4>
    <SystemVersion6>5.0.*</SystemVersion6>
    <DateTimeOnlyVersion>7.0.*</DateTimeOnlyVersion>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.0'))">
    <DefineConstants>$(DefineConstants);NETSTANDARD2_0_COMPAT</DefineConstants>
    <SystemVersion6>6.0.*</SystemVersion6>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.0')) And '$(TargetFramework)' != 'net461'">
    <SystemVersion4>4.6.*</SystemVersion4>
    <SystemVersion6>6.1.*</SystemVersion6>
    <DateTimeOnlyVersion>9.0.*</DateTimeOnlyVersion>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.1'))">
    <DefineConstants>$(DefineConstants);NETSTANDARD2_1_COMPAT</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard1.1'">
    <PolySharpUseEmbeddedAttributeForGeneratedTypes>false</PolySharpUseEmbeddedAttributeForGeneratedTypes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net462'">
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

  <PropertyGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">
    <NoWarn>$(NoWarn);CS1574</NoWarn>
  </PropertyGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="$(SystemVersion6)" />
  </ItemGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">
    <PackageReference Include="Portable.System.DateTimeOnly" Version="$(DateTimeOnlyVersion)" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.0'))" />
  </ItemGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net5.0'))">
    <PackageReference Include="PolySharp" Version="1.16.*" PrivateAssets="All">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Ultz.Bcl.Half" Version="1.0.*" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.0'))" />
  </ItemGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.1'))">
    <PackageReference Include="Nullable" Version="1.3.*" />
    <PackageReference Include="System.Memory" Version="$(SystemVersion4)" />
    <PackageReference Include="System.Numerics.Vectors" Version="$(SystemVersion4)" />
  </ItemGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.0'))">
    <PackageReference Include="System.ValueTuple" Version="$(SystemVersion4)" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SortSharp.Benchmarks" />
    <InternalsVisibleTo Include="SortSharp.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SortSharp.SourceGenerators\SortSharp.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SkipGetTargetFrameworkProperties="true" UndefineProperties="TargetFramework" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <Target Name="AddSourceGeneratorDependencies"
          AfterTargets="ResolveProjectReferences"
          BeforeTargets="CoreCompile">
    <PropertyGroup>
      <_SGDir>$(MSBuildProjectDirectory)\..\SortSharp.SourceGenerators\bin\$(Configuration)\netstandard2.0</_SGDir>
    </PropertyGroup>
    
    <ItemGroup>
      <_SourceGeneratorDependency Include="$(_SGDir)\OneOf.dll;$(_SGDir)\Microsoft.Bcl.HashCode.dll"
                                  Exclude="**\SortSharp.SourceGenerators.dll;**\Microsoft.CodeAnalysis*.dll" />
      <Analyzer Include="@(_SourceGeneratorDependency)" />
    </ItemGroup>
  </Target>

</Project>
