using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using F = Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SortSharp.SourceGenerators.Common;

internal sealed record GeneratedMethod(
    MethodDeclarationSyntax Declaration,
    ImmutableArray<string> Usings,
    string FilePath,
    string Namespace,
    TypeDef TypeName)
{
    internal static IEnumerable<GeneratedFile> Render(
        IEnumerable<GeneratedMethod> variants,
        Func<TypeDeclarationSyntax, TypeDef, TypeDeclarationSyntax> transform)
    {
        return variants
            .GroupBy(v => v.FilePath)
            .Select(f =>
            {
                try
                {
                    var usings = string.Join(
                        "\r\n",
                        f.SelectMany(static v => v.Usings)
                            .Select(static s => s.Trim())
                            .Distinct(StringComparer.Ordinal)
                            .OrderBy(static s => s, StringComparer.Ordinal));
                    var root = F.ParseCompilationUnit($"""
                        // <auto-generated/>
                        #nullable enable
                        {usings}
                        """);

                    var ns = f.Select(static v => v.Namespace).Distinct().Single();
                    var meta = f.First().TypeName;

                    TypeDeclarationSyntax decl = meta.Kind switch
                    {
                        TypeKind.Interface => F.InterfaceDeclaration(meta.Name),
                        TypeKind.Struct => F.StructDeclaration(meta.Name),
                        _ => F.ClassDeclaration(meta.Name),
                    };
                    decl = decl.WithModifiers([F.Token(SyntaxKind.PartialKeyword)])
                        .WithMembers([.. f.Select(static v => v.Declaration)]);
                    if (meta.TypeParameters.Any())
                    {
                        decl = decl
                            .WithTypeParameterList(F.TypeParameterList([.. meta.TypeParameters.Select(F.TypeParameter)]))
                            .WithMembers([.. decl.Members]);
                        decl = transform(decl, meta);
                    }
                    if (meta.Base is TypeDefCore b)
                    {
                        decl = decl.WithBaseList(F.BaseList([F.SimpleBaseType(b.Syntax)]));
                    }
                    // add modifiers for inner-most nested classes
                    if (meta.Containing is not null)
                    {
                        var modifier = f.Select(n => n.TypeName.Modifier).FirstOrDefault(m => m != default);
                        decl = meta.Modifier != default
                            ? decl.WithModifiers([F.Token(SyntaxKind.InternalKeyword), F.Token(modifier), F.Token(SyntaxKind.PartialKeyword)])
                            : decl.WithModifiers([F.Token(SyntaxKind.InternalKeyword), F.Token(SyntaxKind.PartialKeyword)]);
                    }

                    TypeDefCore? c = meta.Containing;
                    while (c is not null)
                    {
                        decl = F.ClassDeclaration(c.Name)
                            .WithModifiers([F.Token(SyntaxKind.PartialKeyword)])
                            .WithMembers([decl]);
                        if (c.TypeParameters.Any())
                        {
                            decl = decl
                                .WithTypeParameterList(F.TypeParameterList([.. c.TypeParameters.Select(F.TypeParameter)]))
                                .WithMembers([.. decl.Members]);
                        }
                        c = c.Containing;
                    }

                    root = root.WithMembers([F.FileScopedNamespaceDeclaration(F.ParseName(ns))
                        .WithMembers([decl])]);

                    return new GeneratedFile(
                        f.Key,
                        root.NormalizeWhitespace().GetText(Encoding.UTF8));
                }
                catch
                {
                    // TODO: provide a diagnostic for this error
                    throw;
                }
            })
            .Where(f => f is not null);
    }
}

internal sealed record GeneratedFile(
    string FilePath,
    SourceText Source);
